### ISSUE TITLE
dockerize

### ISSUE THREAD

**Issue by azimut** [sonidosmutantes/apicultor#17]
https://hub.docker.com/_/ubuntu/

Haria mas facil probar el setup en no-ubuntu distros. No tiene porque ser 1 imagen. Pueden ser mas o reutilizar otras online.

**Comment by hordiales** [comment]
Si, de hecho empecé a armarme un docker para usarlo. Si avanzas en algo con eso avisá y lo publicamos

**Comment by hordiales** [comment]
Azimut nos queres dar una mano con esto?

**Comment by azimut** [comment]
Si tan solo pudiese haber hecho andar este proyecto una sola vez diria que si :P. Voy a intentarlo este finde semana.

**Comment by hordiales** [comment]
Buenísimo @azimut ahi lo estuve probando, vino muy bien tu contribución para avanzar!!

Fijate que actualicé un poco la documentación

Ese error a mi también me pasaba y pasa independientemente de docker. Es algo de Essentia.

En algún update volvió a quedar activado el análisis de logattacktime, que es uno de los que provoca siempre ese tipo de errores. Ahi va mejor
